/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Traseu {
    denumire?: string;

    dificultate?: Traseu.DificultateEnum;

    id?: number;

    lungime?: number;

    tipTraseu?: Traseu.TipTraseuEnum;

}
export namespace Traseu {
    export enum DificultateEnum {
        Greu = <any> 'greu',
        Mediu = <any> 'mediu',
        Usor = <any> 'usor'
    }
    export enum TipTraseuEnum {
        XC = <any> 'XC',
        ENDURO = <any> 'ENDURO',
        DH = <any> 'DH',
        ROAD = <any> 'ROAD',
        SLOPE = <any> 'SLOPE'
    }
}
